// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package spec

import (
	"time"
)

const (
	ApiKeyAuthScopes apiKeyAuthContextKey = "ApiKeyAuth.Scopes"
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for MessageRole.
const (
	Assistant MessageRole = "assistant"
	Tool      MessageRole = "tool"
	User      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case Tool:
		return true
	case User:
		return true
	default:
		return false
	}
}

// ChatRequest defines model for ChatRequest.
type ChatRequest struct {
	// Message The user message to send to the agent
	Message string `json:"message"`

	// Model Optional model override
	Model *string `json:"model,omitempty"`

	// SessionId Continue an existing session (omit to start a new one)
	SessionId *string `json:"session_id,omitempty"`

	// Stream Use SSE streaming for the response
	Stream *bool `json:"stream,omitempty"`
}

// ChatResponse defines model for ChatResponse.
type ChatResponse struct {
	Model     *string `json:"model,omitempty"`
	Response  *string `json:"response,omitempty"`
	SessionId *string `json:"session_id,omitempty"`
	TokensIn  *int    `json:"tokens_in,omitempty"`
	TokensOut *int    `json:"tokens_out,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code  *string `json:"code,omitempty"`
	Error *string `json:"error,omitempty"`
}

// Message defines model for Message.
type Message struct {
	Content   *string      `json:"content,omitempty"`
	CreatedAt *time.Time   `json:"created_at,omitempty"`
	Id        *string      `json:"id,omitempty"`
	Role      *MessageRole `json:"role,omitempty"`
	SessionId *string      `json:"session_id,omitempty"`
}

// MessageRole defines model for Message.Role.
type MessageRole string

// Session defines model for Session.
type Session struct {
	CreatedAt    *time.Time `json:"created_at,omitempty"`
	Id           *string    `json:"id,omitempty"`
	MessageCount *int       `json:"message_count,omitempty"`
	Model        *string    `json:"model,omitempty"`
	UpdatedAt    *time.Time `json:"updated_at,omitempty"`
}

// Stats defines model for Stats.
type Stats struct {
	ActiveSessions *int `json:"active_sessions,omitempty"`
	TokensIn       *int `json:"tokens_in,omitempty"`
	TokensOut      *int `json:"tokens_out,omitempty"`
	TotalMessages  *int `json:"total_messages,omitempty"`
	TotalSessions  *int `json:"total_sessions,omitempty"`
}

// apiKeyAuthContextKey is the context key for ApiKeyAuth security scheme
type apiKeyAuthContextKey string

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// GetV1SessionsParams defines parameters for GetV1Sessions.
type GetV1SessionsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetV1SessionsIdMessagesParams defines parameters for GetV1SessionsIdMessages.
type GetV1SessionsIdMessagesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostV1ChatJSONRequestBody defines body for PostV1Chat for application/json ContentType.
type PostV1ChatJSONRequestBody = ChatRequest
